name: Rebuild Docs

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, review_requested]
    branches-ignore:
      - "gh-pages"
  push:
    branches:
      - "master"
      - "prepare-release"
      - "doc-workflow"
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_website:
    name: Build website
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v6
      - name: Create Gemfile
        run: |
          echo $'source "https://rubygems.org"\n\ngem "jekyll"\n' > Gemfile
      - name: Setup Ruby and Jekyll
        uses: ruby/setup-ruby@8d27f39a5e7ad39aebbcbd1324f7af020229645c  # v1.287.0
        with:
          ruby-version: '4.0.1'
          bundler-cache: true
      - name: Build jsonnet binary
        run: |
          make jsonnet
      - name: Build website
        run: |
          WORKDIR="$(mktemp -d)"
          trap "rm -rf "${WORKDIR}" EXIT
          tools/scripts/update_web_content.sh
          jekyll build -s doc -d "$WORKDIR"
          # Keep existing libjsonnet.wasm.
          WASM_PATH="$WORKDIR"/js/libjsonnet.wasm
          [[ ! -e "$WASM_PATH ]] || \
            { git cat-file blob HEAD:js/libjsonnet.wasm > "$WASM_PATH" ; }
